x = [
    "flink",
    "run-application",
    "--target",
    "kubernetes-application",
    "--parallelism",
    "2",
    "-Dtaskmanager.memory.process.size=2048m",
    "-Dtaskmanager.memory.task.off-heap.size=256m",
    "-Dtaskmanager.memory.framework.off-heap.size=256m",
    "-Dtaskmanager.memory.task.heap.size=700m",
    "-Dtaskmanager.memory.managed.fraction=0.1",
    "-Dkubernetes.taskmanager.cpu=2",
    "-Dtaskmanager.numberOfTaskSlots=2",
    "-Ds3.access-key=HPUARYQNDOMTNIEWUGQI",
    "-Ds3.secret-key=IyEYJyOyrAWzKI54kRCrZjahZnbTGypHnG6IFU8l",
    "-Ds3.endpoint=https://obs.cn-north-4.myhuaweicloud.com",
    "-Ds3.path.style.access=true",
    "-Dkubernetes.container.image.ref=swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-hadoop-3.3.6:1.2",
    "-Dkubernetes.decorator.hadoop-conf-mount.enabled=false",
    "-Dcontainerized.master.env.LAKESOUL_PG_DRIVER=com.lakesoul.shaded.org.postgresql.Driver",
    "-Dcontainerized.master.env.LAKESOUL_PG_USERNAME=lakesoul_e2e",
    "-Dcontainerized.master.env.LAKESOUL_PG_PASSWORD=lakesoul_e2e",
    "-Dcontainerized.master.env.LAKESOUL_PG_URL=jdbc:postgresql://pgsvc.default.svc.cluster.local:5432/lakesoul_e2e?stringtype=unspecified",
    "-Dcontainerized.taskmanager.env.LAKESOUL_PG_DRIVER=com.lakesoul.shaded.org.postgresql.Driver",
    "-Dcontainerized.taskmanager.env.LAKESOUL_PG_USERNAME=lakesoul_e2e",
    "-Dcontainerized.taskmanager.env.LAKESOUL_PG_PASSWORD=lakesoul_e2e",
    "-Dcontainerized.taskmanager.env.LAKESOUL_PG_URL=jdbc:postgresql://pgsvc.default.svc.cluster.local:5432/lakesoul_e2e?stringtype=unspecified",
    "--class",
    "com.dmetasoul.e2e.Main",
    "-Dkubernetes.namespace=jiax",
    "-Dkubernetes.pod-template-file.default=k8s/flink-pod.yaml",
    "-Dkubernetes.cluster-id=creattable-add1l16l-flink",
    "-Djobmanager.archive.fs.dir=s3://lakesoul-e2e/tests/flink/completed-jobs/creattable-add1l16l-flink",
    "s3://lakesoul-e2e/tests/creattable-add1l16l-flink/jars/e2e-3.0.0-SNAPSHOT.jar",
]

print(" ".join(x))
