add_rules("mode.debug", "mode.release")

target("main")
    add_files("src/*.cpp")
    add_includedirs("include")
    add_deps("arrow")
target_end()

target("arrow")
    set_kind("shared")
    add_files()
    add_includedirs("../.venv/lib/python3.8/site-packages/pyarrow/include", {interface = true})
    add_links("arrow")
    add_linkdirs("../.venv/lib/python3.8/site-packages/pyarrow")
target_end()